name: Repository Maintenance

on:
  push:
    paths:
      - labels.yml
    branches: [main]
  workflow_dispatch:

permissions: {}

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - name: Install github-label-sync
        run: npm install -g @endbug/github-label-sync
      - name: Sync labels
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          github-label-sync \
            --labels labels.yml \
            --allow-added-labels \
            ${{ github.repository }}
